version : 0.0.1
title: Panzj'bolg
tagline: Developing Software is Fun!
description: Developing Software is Fun! Developing Software is Fun!

baseurl: ""
url: "http://panzj.github.io"
# url: "http://127.0.0.1:4000"
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - README.md
  - LICENSE
permalink: /:categories/:title.html
paginate: 8
paginate_path: page/:num

markdown: redcarpet
highlighter: pygments # pygments rouge

twitter_username: marvelousowl
github_username:  panzj
author :
  name : panzj
  email : panzj1940@gmail.com
  github: panzj
  avatar: /assets/images/avatar.jpg
  intro: Iâ€™m a developer from the UK who also enjoys photography. I wrote a couple of books about PHP and JavaScript. Currently procrastinating about writing another.
  social:
    - icon: github-circled
      url: https://github.com/panzj
      desc: Fork me on github

    - icon: weibo
      url:  http://weibo.com/panzj1940
      desc: Follow me on weibo

    - icon: twitter
      url:  https://twitter.com/MarvelousOwl
      desc: Follow me on twitter

    - icon: tencent-weibo
      url:  http://t.qq.com/MarvelousOwl
      desc: Follow me on tencent weibo

disqus:
  account: marvelousowl
google:
  search_engine_ID: 014096054277178994371:ulz0rt4ph28
  analytics_Tracking_ID: UA-61445130-1
